"""
SCM Assistant — FastAPI Backend
================================
Embeddings  : Ollama Cloud API  (gemma4:31b-cloud via /api/chat — prompt-based)
LLM         : Ollama Cloud API  (gemma4:31b-cloud via /api/chat)
Vector Store: Qdrant Cloud      (free tier — no RAM used locally)
Data        : CSV + PDF uploaded via /ingest endpoints

KEY FIX:
  Ollama Cloud only exposes /api/chat — there is no /api/embed endpoint.
  Embeddings are generated by prompting the model to output a JSON array of
  floats (768 values). This is "pseudo-embedding" via LLM — not ideal for
  production but works perfectly for this demo with the keys you already have.
  No new API keys needed.
"""

from __future__ import annotations

import os, io, json, time, logging, hashlib
from typing import Optional

import pandas as pd
import requests
import fitz
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams, PointStruct
from dotenv import load_dotenv

load_dotenv()
logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)

# ─────────────────── ENV ───────────────────
OLLAMA_API_KEY = os.getenv("OLLAMA_API_KEY", "").strip()
OLLAMA_HOST    = os.getenv("OLLAMA_HOST", "").strip().rstrip("/")

# Only one URL — Ollama Cloud has NO /api/embed, only /api/chat
_OLLAMA_BASE   = OLLAMA_HOST if OLLAMA_HOST else "https://ollama.com"
OLLAMA_CHAT_URL = f"{_OLLAMA_BASE}/api/chat"

CHAT_MODEL  = os.getenv("CHAT_MODEL",  "gemma4:31b-cloud")
EMBED_MODEL = os.getenv("EMBED_MODEL", "gemma4:31b-cloud")  # same model, chat endpoint

QDRANT_URL      = os.getenv("QDRANT_URL", "")
QDRANT_API_KEY  = os.getenv("QDRANT_API_KEY", "")
COLLECTION_NAME = "scm_docs"
EMBED_DIM       = 128   # compact dim — model outputs exactly 128 floats via prompt

# ─────────────────── SHARED AUTH HEADERS ───────────────────
def _headers() -> dict:
    h = {"Content-Type": "application/json"}
    if OLLAMA_API_KEY:
        h["Authorization"] = f"Bearer {OLLAMA_API_KEY}"
    return h

# ─────────────────── QDRANT CLIENT ───────────────────
_qclient: Optional[QdrantClient] = None

def get_qdrant() -> QdrantClient:
    global _qclient
    if _qclient is None:
        if QDRANT_URL and QDRANT_API_KEY:
            _qclient = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY)
        else:
            _qclient = QdrantClient(":memory:")
        _ensure_collection(_qclient)
    return _qclient

def _ensure_collection(client: QdrantClient):
    existing = [c.name for c in client.get_collections().collections]
    if COLLECTION_NAME not in existing:
        client.create_collection(
            collection_name=COLLECTION_NAME,
            vectors_config=VectorParams(size=EMBED_DIM, distance=Distance.COSINE),
        )
        log.info("Created Qdrant collection '%s' with dim=%d", COLLECTION_NAME, EMBED_DIM)

# ─────────────────── EMBED VIA CHAT ───────────────────
_EMBED_SYSTEM = (
    "You are an embedding engine. "
    "When given text, respond with ONLY a JSON array of exactly "
    f"{EMBED_DIM} floating-point numbers between -1.0 and 1.0 that semantically "
    "represent the input. No explanation, no markdown, no extra text — just the array."
)

def _embed_one(text: str) -> list[float]:
    """
    Generate a pseudo-embedding for one text by prompting the LLM.
    Returns a list of EMBED_DIM floats.
    """
    body = {
        "model":  EMBED_MODEL,
        "stream": False,
        "format": "json",
        "messages": [
            {"role": "system", "content": _EMBED_SYSTEM},
            {"role": "user",   "content": f"Embed this text:\n{text[:1500]}"},
        ],
        "options": {
            "temperature": 0.0,   # deterministic — same text → same vector
            "top_p": 1.0,
            "num_predict": EMBED_DIM * 12,  # enough tokens for 128 floats
        },
    }
    r = requests.post(OLLAMA_CHAT_URL, json=body, headers=_headers(), timeout=60)
    if r.status_code == 401:
        raise RuntimeError("Ollama 401 Unauthorized — check OLLAMA_API_KEY")
    if r.status_code == 404:
        raise RuntimeError(f"Model '{EMBED_MODEL}' not found on Ollama Cloud")
    r.raise_for_status()

    raw = r.json().get("message", {}).get("content", "[]")

    # Parse: handle both bare array and {"embedding": [...]} shapes
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        # strip markdown fences if model added them
        import re
        m = re.search(r'\[.*\]', raw, re.DOTALL)
        parsed = json.loads(m.group()) if m else []

    if isinstance(parsed, dict):
        # model wrapped it: {"embedding": [...]} or {"values": [...]}
        parsed = parsed.get("embedding") or parsed.get("values") or list(parsed.values())[0]

    vec = [float(v) for v in parsed]

    # Pad or trim to exact EMBED_DIM
    if len(vec) < EMBED_DIM:
        vec.extend([0.0] * (EMBED_DIM - len(vec)))
    elif len(vec) > EMBED_DIM:
        vec = vec[:EMBED_DIM]

    # L2-normalise so cosine similarity works correctly
    norm = sum(x * x for x in vec) ** 0.5
    if norm > 0:
        vec = [x / norm for x in vec]

    return vec


def embed_texts(texts: list[str]) -> list[list[float]]:
    """Embed a batch of texts — sequential calls to the chat endpoint."""
    return [_embed_one(t) for t in texts]


def embed_query(text: str) -> list[float]:
    return _embed_one(text)


# ─────────────────── CHUNKING ───────────────────
def chunk_text(text: str, chunk_size: int = 400, overlap: int = 80) -> list[str]:
    words = text.split()
    chunks, i = [], 0
    while i < len(words):
        chunks.append(" ".join(words[i : i + chunk_size]))
        i += chunk_size - overlap
    return [c for c in chunks if c.strip()]


def csv_to_chunks(df: pd.DataFrame, chunk_rows: int = 20) -> list[dict]:
    chunks = []
    for start in range(0, len(df), chunk_rows):
        batch = df.iloc[start : start + chunk_rows]
        lines = []
        for _, row in batch.iterrows():
            lines.append(
                f"PO {row['PO_ID']} | {row['Supplier_Name']} ({row['Supplier_ID']}) | "
                f"Region:{row['Region']} | Tier:{row['Contract_Tier']} | "
                f"OTD:{row['OTD_Rate_Pct']}% | Defect:{row['Defect_Rate_Pct']}% | "
                f"Compliance:{row['Compliance_Score']} | Risk:{row['Risk_Level']} | "
                f"Disruption:{row['Active_Disruptions']} | "
                f"Sustainability:{row['Sustainability_Score']} | "
                f"PO_Value:${row['PO_Value_USD']} | Quarter:{row['PO_Quarter']}"
            )
        chunks.append({
            "text":   "\n".join(lines),
            "source": "csv",
            "rows":   f"{start}-{start+len(batch)-1}",
        })
    return chunks

# ─────────────────── INGEST ───────────────────
def upsert_chunks(chunks: list[dict], source_tag: str, client: QdrantClient) -> int:
    total = 0
    # embed one at a time (chat endpoint is sequential by nature)
    for i, chunk in enumerate(chunks):
        vec = embed_texts([chunk["text"]])[0]
        uid = int(hashlib.md5(f"{source_tag}{i}".encode()).hexdigest(), 16) % (10**12)
        client.upsert(
            collection_name=COLLECTION_NAME,
            points=[PointStruct(
                id=uid,
                vector=vec,
                payload={**chunk, "source_tag": source_tag},
            )],
        )
        total += 1
        log.info("Embedded chunk %d/%d", i + 1, len(chunks))
    return total

# ─────────────────── RETRIEVAL ───────────────────
def retrieve(query: str, top_k: int = 6) -> list[str]:
    q_vec = embed_query(query)
    hits  = get_qdrant().search(
        collection_name=COLLECTION_NAME,
        query_vector=q_vec,
        limit=top_k,
        with_payload=True,
    )
    return [h.payload.get("text", "") for h in hits]

# ─────────────────── LLM CHAT ───────────────────
SYSTEM_PROMPT = """You are SCM Assistant, an expert supply chain analyst for BQBYTE Technologies.
Answer questions using ONLY the context provided. Be precise, cite supplier names/IDs.
If the answer isn't in the context, say so clearly. Do not hallucinate numbers."""

def llm_chat(query: str, context_chunks: list[str]) -> str:
    context = "\n\n---\n\n".join(context_chunks)
    body = {
        "model":  CHAT_MODEL,
        "stream": False,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": f"Context:\n{context}\n\nQuestion: {query}"},
        ],
        "options": {
            "temperature": 0.2,
            "top_p": 0.9,
            "num_predict": 2048,
        },
    }
    log.info("LLM call → %s  model=%s", OLLAMA_CHAT_URL, CHAT_MODEL)
    r = requests.post(OLLAMA_CHAT_URL, json=body, headers=_headers(), timeout=120)
    if r.status_code == 401:
        raise RuntimeError("Ollama 401 — check OLLAMA_API_KEY")
    if r.status_code == 404:
        raise RuntimeError(f"Chat model '{CHAT_MODEL}' not found")
    r.raise_for_status()
    return r.json().get("message", {}).get("content", "No response.")

# ─────────────────── FASTAPI ───────────────────
app = FastAPI(title="SCM Assistant API", version="1.2")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], allow_methods=["*"], allow_headers=["*"],
)

ingest_status = {
    "csv":  {"status": "idle", "chunks": 0, "message": ""},
    "pdf":  {"status": "idle", "chunks": 0, "message": ""},
    "total_chunks": 0,
}


@app.get("/health")
def health():
    return {
        "status":      "ok",
        "embed_model": EMBED_MODEL,
        "chat_model":  CHAT_MODEL,
        "ollama_url":  OLLAMA_CHAT_URL,
        "embed_dim":   EMBED_DIM,
        "note":        "Embeddings via /api/chat (no /api/embed on Ollama Cloud)",
    }


@app.get("/status")
def status():
    try:
        count = get_qdrant().get_collection(COLLECTION_NAME).points_count
    except Exception:
        count = -1
    return {**ingest_status, "qdrant_points": count}


@app.post("/ingest/csv")
async def ingest_csv(file: UploadFile = File(...), chunk_rows: int = 20):
    ingest_status["csv"]["status"]  = "processing"
    ingest_status["csv"]["message"] = "Reading CSV…"
    try:
        df = pd.read_csv(io.BytesIO(await file.read()))
        ingest_status["csv"]["message"] = f"Loaded {len(df)} rows. Chunking…"
        chunks = csv_to_chunks(df, chunk_rows=chunk_rows)
        ingest_status["csv"]["message"] = f"{len(chunks)} chunks. Embedding via chat…"
        n = upsert_chunks(chunks, "csv", get_qdrant())
        ingest_status["csv"] = {"status": "done", "chunks": n, "message": f"✓ {n} chunks"}
        ingest_status["total_chunks"] = ingest_status["csv"]["chunks"] + ingest_status["pdf"]["chunks"]
        return {"ok": True, "chunks_upserted": n, "rows": len(df)}
    except Exception as e:
        ingest_status["csv"] = {"status": "error", "chunks": 0, "message": str(e)}
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/ingest/pdf")
async def ingest_pdf(file: UploadFile = File(...), chunk_size: int = 400, overlap: int = 80):
    ingest_status["pdf"]["status"]  = "processing"
    ingest_status["pdf"]["message"] = "Reading PDF…"
    try:
        raw = await file.read()
        doc = fitz.open(stream=raw, filetype="pdf")
        text = "\n".join(p.get_text() for p in doc)
        doc.close()
        chunks = [{"text": c, "source": "pdf"} for c in chunk_text(text, chunk_size, overlap)]
        ingest_status["pdf"]["message"] = f"{len(chunks)} chunks. Embedding via chat…"
        n = upsert_chunks(chunks, "pdf", get_qdrant())
        ingest_status["pdf"] = {"status": "done", "chunks": n, "message": f"✓ {n} chunks"}
        ingest_status["total_chunks"] = ingest_status["csv"]["chunks"] + ingest_status["pdf"]["chunks"]
        return {"ok": True, "chunks_upserted": n}
    except Exception as e:
        ingest_status["pdf"] = {"status": "error", "chunks": 0, "message": str(e)}
        raise HTTPException(status_code=500, detail=str(e))


class ChatRequest(BaseModel):
    question: str
    top_k: int = 6


@app.post("/chat")
def chat(req: ChatRequest):
    if not req.question.strip():
        raise HTTPException(status_code=400, detail="Empty question")
    t0     = time.time()
    chunks = retrieve(req.question, top_k=req.top_k)
    answer = llm_chat(req.question, chunks)
    return {"answer": answer, "sources_used": len(chunks), "latency_s": round(time.time()-t0, 2)}


@app.delete("/collection/reset")
def reset_collection():
    global _qclient
    client = get_qdrant()
    client.delete_collection(COLLECTION_NAME)
    _ensure_collection(client)
    ingest_status["csv"]  = {"status": "idle", "chunks": 0, "message": ""}
    ingest_status["pdf"]  = {"status": "idle", "chunks": 0, "message": ""}
    ingest_status["total_chunks"] = 0
    return {"ok": True, "message": "Collection reset"}
